# Generated by Django 3.2.9 on 2022-01-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_alter_driver_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
