# Generated by Django 3.2.9 on 2022-01-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_driver_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='contact',
            new_name='email',
        ),
        migrations.AddField(
            model_name='driver',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
