# Generated by Django 3.2.9 on 2022-01-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_auto_20220111_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='charge',
            field=models.IntegerField(blank=True, default=600),
        ),
    ]
