# Generated by Django 3.2.9 on 2022-01-12 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0007_auto_20220112_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='customer',
        ),
    ]
