# Generated by Django 3.2.9 on 2022-01-13 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_supplier'),
        ('shop', '0006_product_description'),
    ]

    operations = [
    ]
